#!/bin/bash
FILES=$(for i in $(find src | grep asm); do echo $i; done)

SUCCESS=1

for f in $FILES; do
    FNAME=$(basename $f .asm)
    nasm -l "${FNAME}.lst" -f elf32 -Idata -o "obj/${FNAME}.o" $f || SUCCESS=0
    if [ $SUCCESS -eq 0 ]; then
        echo "Compilation failure."
        exit 1
    fi
done

OBJS=$(for i in $FILES; do echo "obj/$(basename $i)"; done)

gcc -m32 -march=i386 -o main $(echo $OBJS | sed -re 's/\.asm/.o/g')
rm obj/*.o
