#!/bin/bash
FILES='main.asm
       print_routines.asm
       str_routines.asm
       mem.asm'

SUCCESS=1

for f in $FILES; do
    nasm -f elf32 $f || SUCCESS=0
    if [ $SUCCESS -eq 0 ]; then
        echo "Compilation failure."
        exit 1
    fi
done

gcc -m32 -march=i386 -o main $(echo $FILES | sed -re 's/\.asm/.o/g')
rm *.o
